### ISSUE TITLE
Feature Request : poster le message sur discord automatiquement

### ISSUE THREAD

**Issue by theoludwig** [ArthurDelamare/ligue-ticktick#1]
Salut 👋,

Idée de fonctionnalité : La possibilité que ça poste directement sur discord sur le bon channel grâce à un argument en CLI.
Via OAuth2, ça ne fonctionnerai pas car tu ne pourrais pas poster des messages mais tu peux faire ça grâce au token Discord de la personne avec une nouvelle variable d'environnement dans le fichier .env.

**Comment by ArthurDelamare** [comment]
Bonne idée ! Par contre, je n'ai pas trouvé de documentation concernant l'utilisation d'un token utilisateur pour envoyer des messages sur un serveur. Est-ce que tu as des infos concernant la façon de faire ou de la doc ?

**Comment by theoludwig** [comment]
Il faut faire une requête POST à cette adresse de l'API de discord : /channels/{channel.id}/messages : https://discord.com/developers/docs/resources/channel#create-message, en remplacant bien évidemment {channel.id} par le channel correspondant et dans le header la propriété 'Authorization' avec comme valeur le token de la personne, pour récupérer ton token il y a plusieurs façons de faire, par exemple avec cette vidéo : https://www.youtube.com/watch?v=WWHZoa0SxCc.
Le problème c'est qu'il me semble que le channel.id est différent pour tout le monde donc faut d'abord faire une autre requête pour récup les channels et avoir le bon id, et puis en même temps ça sera un peu plus dynamique.

J'ai vu que tu utilises axios, si tu veux je te ferrais une pull-request dans la semaine en respectant ton eslint et prettier.
Tu en penses quoi du flag --discord et -d ?

**Comment by ArthurDelamare** [comment]
Merci d'avoir pris le temps de me détailler le processus ! La solution m'a l'air viable et le flag --discord et -d est très bien. Si tu as le temps, je serais ravi d'analyser et accepter ta pull-request. Si tu as des questions sur le fonctionnement (qui reste basique) de l'application, n'hésite pas. Sinon, j'essaierai la connexion à Discord dans les prochaines semaines.

**Comment by theoludwig** [comment]
D'ailleurs  je m'étais trompé dans le processus :
> Le problème c'est qu'il me semble que le channel.id est différent pour tout le monde 

Enfaite Le channel.id est pareil pour tout le monde, j'ai confondu avec les MP, donc j'ai préférais le stocker dans une constante en dur dans le code, comme ça même si le nom du channel change, ça fonctionnera toujours.
